//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLDVPOEPART3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Driver1
    {
        public int DriverID { get; set; }
        public string Driver_Name { get; set; }
        public string Driver_Address { get; set; }
        public string Email { get; set; }
        public int Mobile { get; set; }
    }
}
