//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CLDVPOEPART3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rental
    {
        public string CarNo { get; set; }
        public string IName { get; set; }
        public string Driver_Name { get; set; }
        public int RentFee { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime End_Date { get; set; }
        public int RentalID { get; set; }
    
        public virtual Car Car { get; set; }
    }
}
